server {
    listen 80;
    server_name tresjoyeria.com www.tresjoyeria.com;
    # Certbot usará este bloque para validar el dominio
    # y luego lo reemplazará con la config HTTPS automáticamente
}
